name:                bulk
version:             0.1.0.0
github:              "kephas/bulk-haskell"
license:             BSD3
author:              "Pierre Thierry"
maintainer:          "pierre@nothos.net"
copyright:           "2017–2021 Pierre Thierry"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            BULK library for Haskell
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         BULK library for Haskell

dependencies:
- base >= 4.7 && < 5
- bits
- bytestring
- digits
- text

language: Haskell2010

default-extensions:
- ImportQualifiedPost

library:
  source-dirs: src
  dependencies:
    - largeword
    - binary
    - containers
    - extra
    - megaparsec

executables:
  bulk-cli:
    source-dirs:	 app
    main:			 Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - bulk
    - relude
    - filepath
    - optparse-simple

tests:
  bulk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - bulk
    - digits
    - hspec
    - binary
    - quickcheck-instances
    - QuickCheck
    - random
    - string-interpolate
